branches:
  except:
    - /travis-.*/

before_build:
  - nuget restore nunit.sln

build_script: 
  - ps: .\build.ps1 -Target "Appveyor"

# AppVeyor defaults to just its build number
version: '{build}'
# disable built-in tests.
test: off